# Generated by Django 6.1.1 on 2026-09-10 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('joy', models.FloatField(blank=True, null=True)),
                ('sadness', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'channels',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('duration', models.FloatField()),
                ('joy', models.FloatField(blank=True, null=True)),
                ('sadness', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=50)),
                ('views', models.IntegerField()),
                ('channel', models.ForeignKey(db_column='channel_id', on_delete=django.db.models.deletion.CASCADE, to='social_media.channel')),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='social_media.event')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=200)),
                ('message', models.ForeignKey(db_column='message_id', on_delete=django.db.models.deletion.CASCADE, to='social_media.message')),
            ],
            options={
                'db_table': 'sources',
            },
        ),
        migrations.CreateModel(
            name='ChannelConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_views', models.FloatField()),
                ('weight_messages', models.FloatField()),
                ('weight_forwards', models.FloatField()),
                ('channel_1', models.ForeignKey(db_column='id_1', on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='social_media.channel')),
                ('channel_2', models.ForeignKey(db_column='id_2', on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='social_media.channel')),
            ],
            options={
                'db_table': 'channel_connections',
                'unique_together': {('channel_1', 'channel_2')},
            },
        ),
    ]
