# Generated by Django 6.1.1 on 2026-09-11 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelconnection',
            name='channel_1',
            field=models.ForeignKey(db_column='id_1', on_delete=django.db.models.deletion.PROTECT, related_name='connections_from', to='social_media.channel'),
        ),
        migrations.AlterField(
            model_name='channelconnection',
            name='channel_2',
            field=models.ForeignKey(db_column='id_2', on_delete=django.db.models.deletion.PROTECT, related_name='connections_to', to='social_media.channel'),
        ),
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(db_column='channel_id', on_delete=django.db.models.deletion.PROTECT, to='social_media.channel'),
        ),
        migrations.AlterField(
            model_name='message',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.PROTECT, to='social_media.event'),
        ),
        migrations.AlterField(
            model_name='source',
            name='message',
            field=models.ForeignKey(db_column='message_id', on_delete=django.db.models.deletion.PROTECT, to='social_media.message'),
        ),
    ]
